npmRegistries:
    //npm.fontawesome.com:
        npmAlwaysAuth: true
        npmAuthToken: ${FONTAWESOME_NPM_AUTH_TOKEN}

npmScopes:
    fortawesome:
        npmRegistryServer: "https://npm.fontawesome.com"
